services:
  db:
    image: postgres:17.5
    container_name: test_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - "5434:5432"

  redis:
    image: redis:8.0.2
    container_name: test_redis
    command:
      - redis-server
      - "--appendonly yes"
      - "--requirepass ${TEST_REDIS_PASSWORD}"
    ports:
      - "6380:6379"
